// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ilcatsParser.Ef;

namespace ilcatsParser.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ilcatsParser.Ef.Models.CarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("CarModels");
                });

            modelBuilder.Entity("ilcatsParser.Ef.Models.CarSubmodel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CarModelId")
                        .HasColumnType("int");

                    b.Property<string>("Complectations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ModelCode")
                        .HasColumnType("bigint");

                    b.Property<string>("Period")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarModelId");

                    b.HasIndex("ModelCode")
                        .IsUnique();

                    b.ToTable("CarSubmodels");
                });

            modelBuilder.Entity("ilcatsParser.Ef.Models.ComplectationFields.ATMOrMTM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ATMOrMTMs");
                });

            modelBuilder.Entity("ilcatsParser.Ef.Models.ComplectationFields.Body", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bodies");
                });

            modelBuilder.Entity("ilcatsParser.Ef.Models.ComplectationFields.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("ilcatsParser.Ef.Models.ComplectationFields.DriversPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DriversPositions");
                });

            modelBuilder.Entity("ilcatsParser.Ef.Models.ComplectationFields.Engine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Engines");
                });

            modelBuilder.Entity("ilcatsParser.Ef.Models.ComplectationFields.GearShiftType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GearShiftTypes");
                });

            modelBuilder.Entity("ilcatsParser.Ef.Models.ComplectationFields.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("ilcatsParser.Ef.Models.ComplectationFields.NoOfDoors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NoOfDoors");
                });

            modelBuilder.Entity("ilcatsParser.Ef.Models.ComplectationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ATMOrMTMId")
                        .HasColumnType("int");

                    b.Property<int?>("BodyId")
                        .HasColumnType("int");

                    b.Property<int?>("CarSubmodelId")
                        .HasColumnType("int");

                    b.Property<string>("Complectation")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int?>("DriversPositionId")
                        .HasColumnType("int");

                    b.Property<int?>("EngineId")
                        .HasColumnType("int");

                    b.Property<int?>("GearShiftTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("GradeId")
                        .HasColumnType("int");

                    b.Property<int?>("NoOfDoorsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ATMOrMTMId");

                    b.HasIndex("BodyId");

                    b.HasIndex("CarSubmodelId");

                    b.HasIndex("Complectation")
                        .IsUnique()
                        .HasFilter("[Complectation] IS NOT NULL");

                    b.HasIndex("DestinationId");

                    b.HasIndex("DriversPositionId");

                    b.HasIndex("EngineId");

                    b.HasIndex("GearShiftTypeId");

                    b.HasIndex("GradeId");

                    b.HasIndex("NoOfDoorsId");

                    b.ToTable("ComplectationModels");
                });

            modelBuilder.Entity("ilcatsParser.Ef.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ComplectationModelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ComplectationModelId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("ilcatsParser.Ef.Models.Subgroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Subgroups");
                });

            modelBuilder.Entity("ilcatsParser.Ef.Models.CarSubmodel", b =>
                {
                    b.HasOne("ilcatsParser.Ef.Models.CarModel", "CarModel")
                        .WithMany("CarSubmodels")
                        .HasForeignKey("CarModelId");

                    b.Navigation("CarModel");
                });

            modelBuilder.Entity("ilcatsParser.Ef.Models.ComplectationModel", b =>
                {
                    b.HasOne("ilcatsParser.Ef.Models.ComplectationFields.ATMOrMTM", "ATMOrMTM")
                        .WithMany("Complectations")
                        .HasForeignKey("ATMOrMTMId");

                    b.HasOne("ilcatsParser.Ef.Models.ComplectationFields.Body", "Body")
                        .WithMany("Complectations")
                        .HasForeignKey("BodyId");

                    b.HasOne("ilcatsParser.Ef.Models.CarSubmodel", null)
                        .WithMany("ComplectationModels")
                        .HasForeignKey("CarSubmodelId");

                    b.HasOne("ilcatsParser.Ef.Models.ComplectationFields.Destination", "Destination")
                        .WithMany("Complectations")
                        .HasForeignKey("DestinationId");

                    b.HasOne("ilcatsParser.Ef.Models.ComplectationFields.DriversPosition", "DriversPosition")
                        .WithMany("Complectations")
                        .HasForeignKey("DriversPositionId");

                    b.HasOne("ilcatsParser.Ef.Models.ComplectationFields.Engine", "Engine")
                        .WithMany("Complectations")
                        .HasForeignKey("EngineId");

                    b.HasOne("ilcatsParser.Ef.Models.ComplectationFields.GearShiftType", "GearShiftType")
                        .WithMany("Complectations")
                        .HasForeignKey("GearShiftTypeId");

                    b.HasOne("ilcatsParser.Ef.Models.ComplectationFields.Grade", "Grade")
                        .WithMany("Complectations")
                        .HasForeignKey("GradeId");

                    b.HasOne("ilcatsParser.Ef.Models.ComplectationFields.NoOfDoors", "NoOfDoors")
                        .WithMany("Complectations")
                        .HasForeignKey("NoOfDoorsId");

                    b.Navigation("ATMOrMTM");

                    b.Navigation("Body");

                    b.Navigation("Destination");

                    b.Navigation("DriversPosition");

                    b.Navigation("Engine");

                    b.Navigation("GearShiftType");

                    b.Navigation("Grade");

                    b.Navigation("NoOfDoors");
                });

            modelBuilder.Entity("ilcatsParser.Ef.Models.Group", b =>
                {
                    b.HasOne("ilcatsParser.Ef.Models.ComplectationModel", null)
                        .WithMany("Groups")
                        .HasForeignKey("ComplectationModelId");
                });

            modelBuilder.Entity("ilcatsParser.Ef.Models.Subgroup", b =>
                {
                    b.HasOne("ilcatsParser.Ef.Models.Group", null)
                        .WithMany("Subgroups")
                        .HasForeignKey("GroupId");
                });

            modelBuilder.Entity("ilcatsParser.Ef.Models.CarModel", b =>
                {
                    b.Navigation("CarSubmodels");
                });

            modelBuilder.Entity("ilcatsParser.Ef.Models.CarSubmodel", b =>
                {
                    b.Navigation("ComplectationModels");
                });

            modelBuilder.Entity("ilcatsParser.Ef.Models.ComplectationFields.ATMOrMTM", b =>
                {
                    b.Navigation("Complectations");
                });

            modelBuilder.Entity("ilcatsParser.Ef.Models.ComplectationFields.Body", b =>
                {
                    b.Navigation("Complectations");
                });

            modelBuilder.Entity("ilcatsParser.Ef.Models.ComplectationFields.Destination", b =>
                {
                    b.Navigation("Complectations");
                });

            modelBuilder.Entity("ilcatsParser.Ef.Models.ComplectationFields.DriversPosition", b =>
                {
                    b.Navigation("Complectations");
                });

            modelBuilder.Entity("ilcatsParser.Ef.Models.ComplectationFields.Engine", b =>
                {
                    b.Navigation("Complectations");
                });

            modelBuilder.Entity("ilcatsParser.Ef.Models.ComplectationFields.GearShiftType", b =>
                {
                    b.Navigation("Complectations");
                });

            modelBuilder.Entity("ilcatsParser.Ef.Models.ComplectationFields.Grade", b =>
                {
                    b.Navigation("Complectations");
                });

            modelBuilder.Entity("ilcatsParser.Ef.Models.ComplectationFields.NoOfDoors", b =>
                {
                    b.Navigation("Complectations");
                });

            modelBuilder.Entity("ilcatsParser.Ef.Models.ComplectationModel", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("ilcatsParser.Ef.Models.Group", b =>
                {
                    b.Navigation("Subgroups");
                });
#pragma warning restore 612, 618
        }
    }
}
